# Generated by Django 5.1.7 on 2025-03-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(help_text='Amount in paise')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(default='all', max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='revenue_rev_timesta_d49d54_idx'), models.Index(fields=['category'], name='revenue_rev_categor_202327_idx')],
            },
        ),
    ]
