# Generated by Django 5.1.7 on 2025-03-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('voucher_number', models.CharField(max_length=100)),
                ('voucher_type', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('party_name', models.CharField(max_length=255)),
                ('parent_party_name', models.CharField(max_length=255)),
                ('ledger_name', models.CharField(max_length=255)),
                ('parent_ledger_name', models.CharField(max_length=255)),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('round_off_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state_name', models.CharField(max_length=100)),
                ('gst_registration_type_x', models.CharField(max_length=100)),
                ('stock_item_name', models.CharField(max_length=255)),
                ('rate', models.CharField(max_length=50)),
                ('actual_qty', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('gst_registration_type_y', models.CharField(max_length=100)),
                ('opening_balance_ledger', models.DecimalField(decimal_places=2, max_digits=15)),
                ('parent', models.CharField(max_length=255)),
                ('base_units', models.CharField(max_length=50)),
                ('opening_qty', models.CharField(max_length=50)),
                ('opening_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opening_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst_type_of_supply', models.CharField(max_length=100)),
                ('gst_applicable', models.CharField(max_length=100)),
                ('gst_rate', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
