# Generated by Django 5.1.7 on 2025-03-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_masterdata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
