# Generated by Django 5.1.7 on 2025-03-17 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_masterdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.masterdata')),
            ],
        ),
    ]
