# Generated by Django 5.1.7 on 2025-03-19 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_purchasedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedata',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='purchasedata',
            name='master_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_data', to='data.masterdata'),
        ),
    ]
