# Generated by Django 5.1.7 on 2025-03-19 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_purchasedata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedata',
            name='master_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Purchase_data', to='data.masterdata'),
        ),
        migrations.CreateModel(
            name='ContraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Contra_data', to='data.masterdata')),
            ],
        ),
        migrations.CreateModel(
            name='CreditNoteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CreditNote_data', to='data.masterdata')),
            ],
        ),
        migrations.CreateModel(
            name='DebitNoteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DebitNote_data', to='data.masterdata')),
            ],
        ),
        migrations.CreateModel(
            name='JournalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Journal_data', to='data.masterdata')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_data', to='data.masterdata')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_data', to='data.masterdata')),
            ],
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Sales_data', to='data.masterdata')),
            ],
        ),
    ]
