# Generated by Django 5.1.7 on 2025-03-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_branche_country_customertype_gender_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdata',
            name='qty_number',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='masterdata',
            name='qty_unit',
            field=models.CharField(default='na', max_length=100),
        ),
    ]
