# Generated by Django 5.1.7 on 2025-03-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_masterdata_qty_number_masterdata_qty_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdata',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='masterdata',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='masterdata',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
