# Generated by Django 5.1.7 on 2025-04-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('days_present', models.IntegerField(blank=True, null=True)),
                ('absent', models.IntegerField(blank=True, null=True)),
                ('sl_wo_ot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ot_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_hour_rs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ot_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('late', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deduct_25th_adv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deduct_old_adv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_old_advance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance_advance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('incentive', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sal_tds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('advance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
