# Generated by Django 5.2 on 2025-04-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarydata',
            old_name='amt',
            new_name='adv_paid_on_25th',
        ),
        migrations.RenameField(
            model_name='salarydata',
            old_name='balance_advance',
            new_name='basic_salary_per_hour',
        ),
        migrations.RenameField(
            model_name='salarydata',
            old_name='charge',
            new_name='basic_salary_per_minute',
        ),
        migrations.RenameField(
            model_name='salarydata',
            old_name='absent',
            new_name='days_absent',
        ),
        migrations.RenameField(
            model_name='salarydata',
            old_name='deduct_25th_adv',
            new_name='final_balance_advance',
        ),
        migrations.RenameField(
            model_name='salarydata',
            old_name='deduct_old_adv',
            new_name='late_charges',
        ),
        migrations.RenameField(
            model_name='salarydata',
            old_name='grand_total',
            new_name='late_minutes',
        ),
        migrations.RenameField(
            model_name='salarydata',
            old_name='late',
            new_name='net_payable',
        ),
        migrations.RenameField(
            model_name='salarydata',
            old_name='net_salary',
            new_name='repayment_of_old_adv',
        ),
        migrations.RenameField(
            model_name='salarydata',
            old_name='per_hour_rs',
            new_name='sal_before_tds',
        ),
        migrations.RenameField(
            model_name='salarydata',
            old_name='sal_tds',
            new_name='salary_wo_advance_deduction',
        ),
        migrations.RenameField(
            model_name='salarydata',
            old_name='sl_wo_ot',
            new_name='sl_wo_ot_wo_late',
        ),
        migrations.RemoveField(
            model_name='salarydata',
            name='total_salary',
        ),
        migrations.AddField(
            model_name='salarydata',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
