# Generated by Django 5.2 on 2025-04-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0002_rename_amt_salarydata_adv_paid_on_25th_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydata',
            name='days_absent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salarydata',
            name='days_present',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
