# Generated by Django 5.2 on 2025-04-27 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0004_employeeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('calendar_days', models.IntegerField(default=0, help_text='Total calendar days in the month')),
                ('total_working_days', models.IntegerField(default=0, help_text='Total working days excluding holidays and weekends')),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('ot_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('late_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'name'],
                'unique_together': {('employee_id', 'date')},
            },
        ),
    ]
