# Generated by Django 5.2 on 2025-04-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
