# Generated by Django 5.2 on 2025-05-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0007_dailyattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='ot_charge_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
