# Generated by Django 5.2 on 2025-05-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0010_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydata',
            name='total_advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
